# `numpy` revisions


In [1]:
import numpy as np


---


## creating arrays


Create an array with numbers $-1$, $3$, $5$, $7$.


In [2]:
np.array([-1, 3, 5, 7])


array([-1,  3,  5,  7])

Create an array of numbers from $0$ to $10$.


In [3]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array of numbers from $0$ to $120$.


In [4]:
np.arange(120)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

---


## multi-dimensional arrays & reshaping


Create an array of 2 dimensions with 3 rows, and 2 columns matching the following:
1 | 2
3 | 4
5 | 6


In [5]:
np.array([[1, 2], [3, 4], [5, 6]])


array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# or
np.arange(6).reshape(3, 2) + 1


array([[1, 2],
       [3, 4],
       [5, 6]])

Create an array of 3 dimensions with 3 rows, 3 columns, and 3 layers, with entries ranging from $0$ to $26$.


In [7]:
np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
        [[19, 20, 21], [22, 23, 24], [25, 26, 27]],
    ]
)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [8]:
# or
np.arange(27).reshape(3, 3, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Let `a = np.array([[1,2],[3,4],[5,6]])`

- Reshape `a` to a 1D array (name that array `b`)
- Then reshape `b` to a 2D array of 2 lines, and 3 columns (name that array `c`)


In [9]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a.shape)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [10]:
b = a.reshape(6)
print(b)
print(b.shape)


[1 2 3 4 5 6]
(6,)


In [11]:
c = b.reshape((2, 3))
print(c)
print(c.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


---

## Copying

Here is an example that demonstrates the difference between `.view()` and `.copy()`

In [16]:
x = np.array([1, 3, 6])
y = x.copy()
z = x.view()

x[0] = 0
y[1] = 2
z[2] = 5

print('x:', x)
print('y:', y)
print('z:', z)

x: [0 3 5]
y: [1 2 6]
z: [0 3 5]


Study this example, and explain the difference between the two methods

Now look at the following code, what do you expect? what happens in reality?

In [17]:
x = np.array([1, 3, 6])
y = x
x[0] = 0
y[1] = 2

print('x:', x)
print('y:', y)

x: [0 2 6]
y: [0 2 6]


Hence, be careful when you want to maje copies of arrays! (use the `.copy()` method)