# `numpy` revisions


In [1]:
import numpy as np


---


## Creating arrays


Create an array with numbers $-1$, $3$, $5$, $7$.


In [2]:
np.array([-1, 3, 5, 7])


array([-1,  3,  5,  7])

Create an array of numbers from $0$ to $10$.


In [3]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array of numbers from $0$ to $10$ with a step of $0.1$.


In [4]:
np.arange(101) / 10


array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [5]:
# or
np.linspace(0, 10, 101)


array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

---


## Multi-dimensional arrays & Reshaping


Create an array of 2 dimensions with 3 rows, and 2 columns matching the following:

| 1   | 2   |
| --- | --- |
| 3   | 4   |
| 5   | 6   |


In [6]:
np.array([[1, 2], [3, 4], [5, 6]])


array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# or
np.arange(6).reshape(3, 2) + 1


array([[1, 2],
       [3, 4],
       [5, 6]])

Create an array of 3 dimensions with 3 rows, 3 columns, and 3 layers, with entries ranging from $0$ to $26$.


In [8]:
np.array(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
        [[19, 20, 21], [22, 23, 24], [25, 26, 27]],
    ]
)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [9]:
# or
np.arange(27).reshape(3, 3, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Let `a = np.array([[1,2],[3,4],[5,6]])`

- Reshape `a` to a 1D array (name that array `b`)
- Then reshape `b` to a 2D array of 2 lines, and 3 columns (name that array `c`)


In [10]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a.shape)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [11]:
b = a.reshape(6)
print(b)
print(b.shape)


[1 2 3 4 5 6]
(6,)


In [12]:
c = b.reshape((2, 3))
print(c)
print(c.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


---


## Copying


Here is an example that demonstrates the difference between `.view()` and `.copy()`


In [13]:
x = np.array([1, 3, 6])
y = x.copy()
z = x.view()

x[0] = 0
y[1] = 2
z[2] = 5

print("x:", x)
print("y:", y)
print("z:", z)


x: [0 3 5]
y: [1 2 6]
z: [0 3 5]


Study this example, and explain the difference between the two methods


Now look at the following code, what do you expect? what happens in reality?


In [14]:
x = np.array([1, 3, 6])
y = x
x[0] = 0
y[1] = 2

print("x:", x)
print("y:", y)


x: [0 2 6]
y: [0 2 6]


Hence, be careful when you want to maje copies of arrays! (use the `.copy()` method)


---


## Selections & Operations


Create a list of numbers `x` as follows


In [15]:
np.random.seed(0)
x = np.random.randint(10, size=(4, 5))
x


array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

Select the numbers below $5$, as a 1D array.


In [16]:
x[x < 5]


array([0, 3, 3, 3, 2, 4, 1, 1])

Calulate the square root of each number in `x`, store the result in `y`, an array of the same shape as `x`.


In [17]:
y = np.sqrt(x)
y


array([[2.23606798, 0.        , 1.73205081, 1.73205081, 2.64575131],
       [3.        , 1.73205081, 2.23606798, 1.41421356, 2.        ],
       [2.64575131, 2.44948974, 2.82842712, 2.82842712, 1.        ],
       [2.44948974, 2.64575131, 2.64575131, 2.82842712, 1.        ]])

Select the numbers in `x` with square above $5$, as a 1D array.


In [18]:
x[x**2 > 5]


array([5, 3, 3, 7, 9, 3, 5, 4, 7, 6, 8, 8, 6, 7, 7, 8])